version: '3.4'

services:
  vscode:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file: .env


    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:rstudiodevcontainer

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${USER}
        QUARTO_VERSION: ${QUARTO_VERSION}
    user: ${USER}
    volumes:
      - ..:/workspace:cached
      - ${RENV_PATHS_CACHE_HOST}:/renv/cache
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined


  rstudiodevcontainer:
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    env_file: .env
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    #ports:
    #  - ${LOCAL_PORT}:8787
    
    # network_mode: service:vscode

    build:
      context: ./rstudio_docker
      args:
        S6_VERSION: ${S6_VERSION}
        RSTUDIO_VERSION: ${RSTUDIO_VERSION}
        QUARTO_VERSION: ${QUARTO_VERSION}
    #volumes:
    #  - ${VOLUME_PATH}:${VOLUME_PATH}
    #  - /home/${USER}/.ssh:/home/${USER}/.ssh
    #  - ${RENV_PATHS_CACHE_HOST}:${RENV_PATHS_CACHE_CONTAINER}
    #  - ${VOLUME_PATH}/.devcontainer/rstudio_config_dir:/home/${USER}/.config/rstudio
    restart:
      unless-stopped
    #cap_add:
    #  - SYS_PTRACE
    #security_opt:
    #  - seccomp:unconfined

# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3-postgres/.devcontainer/docker-compose.yml
#volumes:
#  postgres-data:
